version: '3.1'

services:
  proxy:
    ports:
      - 9000:9000
    build:
      context: proxy
      dockerfile: Dockerfile
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password