version: '3.1'

services:
  control_plane:
    ports:
      - 50051:50051
    build:
      context: control_plane
  proxy:
    depends_on:
      - control_plane
    ports:
      - 9000:9000
      - 9001:9001
    build:
      context: proxy
  backend:
    depends_on:
      - control_plane
      - proxy
    ports:
      - 8090:8090
    build:
      context: backend
  frontend:
    depends_on:
      - backend
    ports:
      - 3000:3000
    build:
      context: frontend

  # In the future...
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password